# MVS 2.0 Railway 배포 설정

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "staging"
PORT = "3000"

