import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ko: {
    // 기본 메뉴
    logout: '로그아웃',
    language: '언어',
    korean: '한국어',
    english: '영어',
    defaultLanguage: '기본 언어',
    
      // 직원 정보 관리
  userManagement: '직원 정보 관리',
    userList: '사용자 목록',
    userRegister: '사용자 등록',
    userManage: '직원 정보 관리',
    userAdd: '사용자 추가',
    userEdit: '사용자 수정',
    userInfo: '사용자 정보',
    userIdLogin: '사용자 ID (로그인용)',
    usernameReal: '사용자명 (실제 이름)',
    existingPassword: '기존 비밀번호',
    newPasswordLeaveEmpty: '새 비밀번호 (변경하지 않으려면 비워두세요)',
    notSet: '설정되지 않음',
    searchUserPlaceholder: '사용자 ID 또는 이름 검색',
    createDate: '생성일',
    updateDate: '수정일',
    
    // 권한 관리
    permissionManagement: '권한 관리',
    userPermissionManagement: '사용자 권한 관리',
    menuPermissionManagement: '메뉴 권한 관리',
    roleManagement: '역할 관리',
    
    // 메뉴 관리
    menuManagement: '메뉴 관리',
    
    // 회사 관리
    companyManagement: '회사정보 관리',
    companyList: '회사 목록',
    companyAdd: '회사 추가',
    companyEdit: '회사 정보 수정',
    companyDelete: '회사 삭제',
    companyName: '회사명',
    businessNumber: '사업자번호',
    address: '주소',
    pan: 'PAN',
    gst1: 'GST1',
    gst2: 'GST2',
    gst3: 'GST3',
    gst4: 'GST4',
    iec: 'IEC',
    msme: 'MSME',
    bankName: '은행명',
    accountHolder: '계좌소유자',
    accountNumber: '계좌번호',
    ifscCode: 'IFSC 코드',
    registrationDate: '등록일',
    management: '관리',
    noCompanies: '등록된 회사가 없습니다.',
    companyDeleteConfirm: '회사 삭제 확인',
    companyDeleteMessage: '회사를 삭제하시겠습니까?',
    companyDeleteWarning: '이 작업은 되돌릴 수 없습니다.',
    cancel: '취소',
    save: '저장',
    edit: '수정',
    delete: '삭제',
    add: '추가',
    companyDescription: '회사 정보를 관리할 수 있습니다.',
    basicInfo: '기본 정보',
    taxInfo: '세무 정보',
    bankInfo: '은행 정보',
    lastUpdate: '최종 수정일',
    companyType: '회사 타입',
    mvsCustomer: 'MVS 고객회사',
    myCompany: '내 회사',
    myCompanyRoot: '내 회사 (Root)',
    supplier: '공급업체',
    customer: '고객업체',
    supplierAndCustomer: '공급업체 + 고객업체',
    
    // 인보이스 관리
    invoiceManagement: '인보이스 관리',
    invoiceList: '인보이스 목록',
    invoiceCreate: '인보이스 생성',
    invoiceApprove: '인보이스 승인',
    
    // 결제 관리
    paymentManagement: '결제 관리',
    paymentList: '결제 목록',
    paymentWrite: '결제 작성',
    paymentApprove: '결제 승인',
    
    // 전자 결재
    electronicApproval: '전자 결재',
    
    // 업무 관리
    workManagement: '업무 관리',
    workList: '업무 목록',
    workCreate: '업무 지시',
    workEdit: '업무 수정',
    workDelete: '업무 삭제',
    workTitle: '업무 제목',
    workDescription: '업무 내용',
    workStatus: '업무 상태',
    workPriority: '우선순위',
    workAssignee: '수행자',
    workAssigner: '지시자',
    workCategory: '업무 유형',
    workDueDate: '완료 예정일',
    workStartDate: '시작 예정일',
    workCreatedAt: '지시일',
    workUpdatedAt: '수정일',
    workComments: '코멘트',
    addComment: '코멘트 추가',
    noWorks: '등록된 업무가 없습니다.',
    workAccept: '업무 수락',
    workReject: '업무 거부',
    workAttachments: '첨부 파일',
    addAttachment: '파일 첨부',
    
    // 업무 상태
    workPending: '수락 대기',
    workAccepted: '수락됨',
    workInProgress: '진행중',
    workCompleted: '완료',
    workRejected: '거부됨',
    
    // 업무 우선순위  
    workLow: '낮음',
    workNormal: '보통', 
    workHigh: '높음',
    workUrgent: '긴급',
    
    // 업무 카테고리
    workGeneral: '일반업무',
    workProject: '프로젝트',
    workMeeting: '회의',
    workReport: '보고서',
    workPlanning: '기획',
    workReview: '검토',
    electronicApprovalRequest: '전자 결재 요청서',
    electronicApprovalRequestDetails: '전자 결재 요청서 상세',
    requestedApprovals: '요청한 결제',
    receivedApprovals: '받은 결제',
    myRequestedApprovals: '내가 요청한 결제',
    myReceivedApprovals: '내가 받은 결제 요청',
    approvalRequest: '결제 요청',
    approvalDetails: '결제 요청 상세',
    createApprovalRequest: '결제 요청 작성',
    approvalTitle: '제목',
    approvalContent: '내용',
    approvalPriority: '우선순위',
    approvalDueDate: '마감일',
    approvalStatus: '상태',
    approvalRequester: '요청자',
    approvalApprover: '승인자',
    approvalRequestNumber: '요청 번호',
    approvalRequestDate: '요청일자',
    approvalCurrentStatus: '현재 상태',
    approvalPending: '승인 대기',
    approvalApproved: '승인 완료',
    approvalRejected: '거부됨',
    approvalHigh: '높음',
    approvalMedium: '보통',
    approvalLow: '낮음',
    approvalFiles: '첨부 파일',
    attachedFiles: '첨부된 파일',
    fileAttachment: '파일 첨부',
    downloadFile: '파일 다운로드',
    approvalComments: '코멘트',
    commentsAndHistory: '코멘트 및 처리 이력',
    processingHistory: '처리 이력',
    processingHistoryCount: '처리 이력 ({count}개):',
    attachedFilesCount: '첨부된 파일 ({count}개):',
    commentPlaceholder: '코멘트를 입력하세요 (Enter: 등록, Shift+Enter: 줄바꿈)',
    registerComment: '등록',
    approvalCompleted: '승인 완료된 요청입니다. 더 이상 코멘트를 추가할 수 없습니다.',
    approvalRejectedComment: '거부된 요청입니다. 더 이상 코멘트를 추가할 수 없습니다.',
    noCommentsYet: '아직 코멘트가 없습니다.',
    reassignApproval: '결재 재지정',
    reassignToOtherApprover: '다른 승인자에게 다시 전달',
    reassignToAnotherApprover: '다른 승인자에게 결재를 재지정할 수 있습니다.',
    newApprover: '새 승인자',
    selectNewApprover: '새 승인자를 선택하세요...',
    noAvailableApprovers: '승인 가능한 사용자가 없습니다',
    reassignReason: '재지정 사유',
    reassignReasonPlaceholder: '재지정 사유를 입력하세요 (선택)',
    performReassign: '결재 재지정',
    reassignment: '재지정',
    reassignmentWaiting: '승인 대기',
    confirmApproval: '승인',
    rejectApproval: '거부',
    approveRequest: '승인',
    rejectRequest: '거부',
    requestApproval: '결재 요청',
    detailedContent: '상세 내용',
    requestReason: '결제 요청 사유 및 상세 내용을 입력하세요',
    titlePlaceholder: '요청 제목을 입력하세요',
    selectApprover: '승인자를 선택하세요',
    dueDateHelper: '미선택 시 자동으로 3일 후로 설정됩니다',
    documentNumber: '문서 번호',
    creationDate: '작성일자',
    completionDate: '완료 예정일',
    confirmationSection: '확인란',
    categorySection: '구분',
    fullName: '성명',
    confirmation: '확인',
    requestConfirm: '요청',
    approvalWaiting: '승인 대기',
    approvalInfo: '승인 정보',
    requestContent: '요청 내용',
    attachments: '첨부 파일',
    viewAll: '전체보기',
    searchApprovalPlaceholder: '제목, 요청자, 승인자로 검색...',
    noApprovals: '결재 요청이 없습니다.',
    documentInformation: '문서 정보',
    requestedPayments: '내가 요청한 결제',
    receivedPaymentRequests: '내가 받은 결제 요청',
    completionDueDate: '완료 예정일',
    
    // 대시보드 추가 번역
    dashboardTitle: '대시보드',
    recentActivity: '최근 활동',
    systemPerformance: '시스템 성능',
    myRequestedPayments: '내가 요청한 결재',
    myReceivedPaymentRequests: '내가 받은 결재',
    
    // 문서 정보 관련
    department: '부서',
    general: '일반',
    
    // 섹션 제목
    requestContentSection: '1. 요청 내용',
    approvalInfoSection: '2. 승인 정보',
    attachmentSection: '3. 첨부 파일',
    confirmationSectionTitle: '4. 확인란',
    
    // 폼 라벨
    titleLabel: '제목 *',
    detailedContentLabel: '상세 내용 *',
    approverLabel: '승인자 *',
    priorityLabel: '우선순위',
    dueDateLabel: '한료 예정일',
    
    // 테이블 헤더
    categoryHeader: '구분',
    nameHeader: '성명',
    dateHeader: '날짜',
    confirmationHeader: '확인',
    
    // 상태 및 메시지
    approvalWaitingStatus: '승인 대기',
    requestStatus: '요청',
    selectApproverPlaceholder: '승인자를 선택하세요',
    approverReassigned: '승인자를 재지정했습니다.',
    dueDateAutoSet: '* 미선택 시 자동으로 3일 후로 설정됩니다',
    
          // 대시보드 인사말 및 상태
      welcomeMessage: '안녕하세요, {name}님!',
      systemStatusNormal: '정상',
      allServicesActive: '모든 서비스 활성',
      
      // 공지사항
      notice: '공지사항',
      noticeList: '공지사항 목록',
      noticeCreate: '공지사항 작성',
      noticeEdit: '공지사항 수정',
      noticeDelete: '공지사항 삭제',
      noticeTitle: '제목',
      noticeContent: '내용',
      noticeAuthor: '작성자',
      noticePriority: '우선순위',
      noticePriorityHigh: '높음',
      noticePriorityMedium: '보통',
      noticePriorityLow: '낮음',
      noticePinned: '고정 공지사항',
      noticeStartDate: '시작일',
      noticeEndDate: '종료일',
      noticeViewCount: '조회수',
      noticeCreatedAt: '작성일',
      noticeActions: '작업',
      noticeView: '상세보기',
      noticeEditAction: '수정',
      noticeDeleteAction: '삭제',
      noticeDeleteConfirm: '정말로 이 공지사항을 삭제하시겠습니까?',
      noticeSearch: '검색',
      noticeSearchPlaceholder: '제목 또는 내용으로 검색',
      noticeFilterAll: '전체',
      noticeFilterPriority: '우선순위',
      noticeClearSearch: '초기화',
      noticeTotal: '총 {count}개의 공지사항',
    menuPermissions: '메뉴 권한',
    systemStatusTitle: '시스템 상태',
    noReceivedRequests: '받은 결제 요청이 없습니다',
    
    // 시간 표시
    minutesAgo: '분 전',
    hoursAgo: '시간 전',
    dayAgo: '일 전',
    daysAgo: '일 전',
    
    // 승인 상태
    pending: '대기',
    approved: '승인',
    rejected: '거부',
    
    // 통계 라벨
    adminCount: '관리자',
    activeCount: '활성',
    totalCount: '전체',
    unit: '개',
    unitPeople: '명',
    unknown: '알 수 없음',
    
    // 전자결재 페이지 추가 번역
    listDescription: '목록입니다',
    receivedApprovalsDescription: '내가 승인해야 할 결제 목록입니다',
    statusFilter: '상태',
    waitingForApproval: '대기중',
    currentStatus: '현재 상태',

    // 업무 통계 관련
    workStatistics: '업무 통계',
    workStatisticsDashboard: '업무 통계 대시보드',
    workStatisticsDescription: '업무 현황과 성과를 한눈에 파악할 수 있는 종합 통계 정보입니다',
    totalWorks: '전체 업무',
    completionRate: '완료율',
    onTimeRate: '기한 준수율',
    urgentWorks: '긴급 업무',
    workStatusDistribution: '업무 상태별 분포',
    workPriorityDistribution: '우선순위별 분포',
    workCategoryStatus: '카테고리별 업무 현황',
    userWorkStatus: '사용자별 업무 현황',
    monthlyWorkTrend: '월별 업무 생성 추이',
    rejectedStatus: '거부됨',
    dueDate: '마감일',
    
    // 대시보드 통계
    totalUsers: '총 사용자',
    totalMenus: '총 메뉴',
    registeredCompanies: '등록된 회사',
    permissionSettings: '권한 설정',
    admin: '관리자',
    regular: '일반',
    topLevel: '최상위',
    subMenus: '하위',
    recentUsers: '최근 등록된 사용자',
    systemInfo: '시스템 정보',
    currentTime: '현재 시간',
    userRole: '사용자 역할',
    companyId: '회사 ID',
    systemStatus: '시스템 현황을 한눈에 확인하세요',
    searchPlaceholder: '회사명, COI, 주소, PAN 등으로 검색',
    partnerSearchPlaceholder: '파트너사명, COI, 주소, PAN, 취급품목 등으로 검색',
    roleSearchPlaceholder: '역할명, 설명, 레벨, 회사 접근 권한 등으로 검색',
    noSearchResults: '검색 결과가 없습니다',
    searchResults: '개 결과',
    notifications: '알림',
    loading: '메뉴를 불러오는 중...',

    // 대시보드 대체 카드
    approvalOverview: '결재 대기 현황',
    toApprove: '승인할 건',
    requested: '요청한 건',
    
    // 로그인 페이지
    login: '로그인',
    username: '사용자명',
    password: '비밀번호',
    loginButton: '로그인',
    loginError: '로그인에 실패했습니다.',
    invalidCredentials: '사용자명 또는 비밀번호가 올바르지 않습니다.',
    welcomeToManagementSystem: '관리 시스템에 오신 것을 환영합니다',
    enterAccountInfo: '계정 정보를 입력해주세요',
    defaultAccount: '기본 계정: root / admin',
    
    // 시스템 초기화
    systemInitialization: '시스템 초기화',
    initializeSystem: '시스템 초기화',
    systemInitDescription: '시스템을 초기화하여 기본 설정을 구성합니다.',
    initSuccess: '시스템 초기화가 완료되었습니다.',
    initError: '시스템 초기화 중 오류가 발생했습니다.',
    createInitialAdminAccount: '최초 관리자 계정을 생성합니다.',
    passwordMismatch: '비밀번호가 일치하지 않습니다.',
    confirmPassword: '비밀번호 확인',
    initialize: '초기화',
    companyInfo: '회사 정보',
    adminAccount: '관리자 계정',
    menuStructure: '메뉴 구성',
    
    // 예시 페이지
    examplePageTitle: '예시 페이지',
    addItem: '항목 추가',
    editItem: '항목 수정',
    dataLoadError: '데이터를 불러오는데 실패했습니다.',
    deleteConfirm: '정말 삭제하시겠습니까?',
    deleteError: '삭제 중 오류가 발생했습니다.',
    saveError: '저장 중 오류가 발생했습니다.',
    id: 'ID',
    name: '이름',
    description: '설명',
    actions: '작업',
    
    // 사용자 목록 페이지
    userListDescription: '등록된 사용자 목록을 확인할 수 있습니다.',
    noUsers: '등록된 사용자가 없습니다.',
    userDelete: '사용자 삭제',
    userDeleteConfirm: '사용자 삭제 확인',
    userDeleteMessage: '사용자를 삭제하시겠습니까?',
    userDeleteWarning: '이 작업은 되돌릴 수 없습니다.',
    userCreateDate: '생성일',
    userUpdateDate: '수정일',
    
    // 메뉴 권한 관리
    menuPermissionDescription: '메뉴별 사용자 권한을 관리할 수 있습니다.',
    menuTree: '메뉴 트리',
    menuName: '메뉴명',
    menuNameEn: '메뉴명 (영문)',
    menuUrl: '메뉴 URL',
    menuDescription: '메뉴 설명',
    menuOrder: '메뉴 순서',
    menuIcon: '메뉴 아이콘',
    menuParent: '상위 메뉴',
    menuChildren: '하위 메뉴',
    menuAdd: '메뉴 추가',
    menuEdit: '메뉴 수정',
    menuDelete: '메뉴 삭제',
    menuMoveUp: '위로 이동',
    menuMoveDown: '아래로 이동',
    menuDeleteConfirm: '메뉴 삭제 확인',
    menuDeleteMessage: '메뉴를 삭제하시겠습니까?',
    menuDeleteWarning: '이 작업은 되돌릴 수 없습니다.',
    menuAddSuccess: '메뉴가 추가되었습니다.',
    menuEditSuccess: '메뉴가 수정되었습니다.',
    menuDeleteSuccess: '메뉴가 삭제되었습니다.',
    menuMoveSuccess: '메뉴 순서가 변경되었습니다.',
    
    // 공통
    confirm: '확인',
    close: '닫기',
    back: '뒤로',
    next: '다음',
    previous: '이전',
    filter: '필터',
    refresh: '새로고침',
    role: '역할',
    company: '회사',
    searchUsername: '사용자명 검색...',
    export: '내보내기',
    import: '가져오기',
    download: '다운로드',
    upload: '업로드',
    view: '보기',
    details: '상세보기',
    status: '상태',
    active: '활성',
    inactive: '비활성',
    enabled: '사용',
    disabled: '사용안함',
    yes: '예',
    no: '아니오',
    all: '전체',
    none: '없음',
    error: '오류',
    success: '성공',
    warning: '경고',
    info: '정보',
    required: '필수',
    optional: '선택',
    submit: '제출',
    reset: '초기화',
    clear: '지우기',
    select: '선택',
    selectAll: '전체 선택',
    deselectAll: '전체 해제',
    sort: '정렬',
    sortAsc: '오름차순',
    sortDesc: '내림차순',
    page: '페이지',
    of: '중',
    items: '개',
    perPage: '페이지당',
    showing: '표시 중',
    to: '에서',
    from: '부터',
    total: '총',
    empty: '비어있음',
    noData: '데이터가 없습니다',
    retry: '다시 시도',
    reload: '다시 로드',
    copy: '복사',
    paste: '붙여넣기',
    cut: '잘라내기',
    undo: '실행 취소',
    redo: '다시 실행',
    zoomIn: '확대',
    zoomOut: '축소',
    fullscreen: '전체화면',
    exitFullscreen: '전체화면 종료',
    preferences: '환경설정',
    help: '도움말',
    about: '정보',
    contact: '연락처',
    support: '지원',
    feedback: '피드백',
    report: '보고서',
    analytics: '분석',
    home: '홈',
    account: '계정',
    security: '보안',
    privacy: '개인정보',
    terms: '이용약관',
    policy: '개인정보처리방침',
    copyright: '저작권',
    version: '버전',
    build: '빌드',
    date: '날짜',
    time: '시간',
    datetime: '날짜시간',
    today: '오늘',
    yesterday: '어제',
    tomorrow: '내일',
    week: '주',
    month: '월',
    year: '년',
    january: '1월',
    february: '2월',
    march: '3월',
    april: '4월',
    may: '5월',
    june: '6월',
    july: '7월',
    august: '8월',
    september: '9월',
    october: '10월',
    november: '11월',
    december: '12월',
    monday: '월요일',
    tuesday: '화요일',
    wednesday: '수요일',
    thursday: '목요일',
    friday: '금요일',
    saturday: '토요일',
    sunday: '일요일',
  },
  en: {
    // 기본 메뉴
    logout: 'Logout',
    language: 'Language',
    korean: 'Korean',
    english: 'English',
    defaultLanguage: 'Default Language',
    
    // 사용자 관리
    userManagement: 'User Management',
    userList: 'User List',
    userRegister: 'User Register',
    userManage: 'User Manage',
    userAdd: 'Add User',
    userEdit: 'Edit User',
    userInfo: 'User Information',
    userIdLogin: 'User ID (for login)',
    usernameReal: 'Username (real name)',
    existingPassword: 'Existing Password',
    newPasswordLeaveEmpty: 'New Password (leave empty if not changing)',
    notSet: 'Not Set',
    searchUserPlaceholder: 'Search by User ID or Name',
    createDate: 'Create Date',
    updateDate: 'Update Date',
    
    // 권한 관리
    permissionManagement: 'Permission Management',
    userPermissionManagement: 'User Permission Management',
    menuPermissionManagement: 'Menu Permission Management',
    roleManagement: 'Role Management',
    
    // 메뉴 관리
    menuManagement: 'Menu Management',
    
    // 회사 관리
    companyManagement: 'Company Management',
    companyList: 'Company List',
    companyAdd: 'Add Company',
    companyEdit: 'Edit Company',
    companyDelete: 'Delete Company',
    companyName: 'Company Name',
    businessNumber: 'Business Number',
    address: 'Address',
    pan: 'PAN',
    gst1: 'GST1',
    gst2: 'GST2',
    gst3: 'GST3',
    gst4: 'GST4',
    iec: 'IEC',
    msme: 'MSME',
    bankName: 'Bank Name',
    accountHolder: 'Account Holder',
    accountNumber: 'Account Number',
    ifscCode: 'IFSC Code',
    registrationDate: 'Registration Date',
    management: 'Management',
    noCompanies: 'No companies registered.',
    companyDeleteConfirm: 'Delete Company Confirmation',
    companyDeleteMessage: 'Are you sure you want to delete this company?',
    companyDeleteWarning: 'This action cannot be undone.',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    companyDescription: 'You can manage company information.',
    basicInfo: 'Basic Information',
    taxInfo: 'Tax Information',
    bankInfo: 'Bank Information',
    lastUpdate: 'Last Update',
    companyType: 'Company Type',
    mvsCustomer: 'MVS Customer',
    myCompany: 'My Company',
    myCompanyRoot: 'My Company (Root)',
    supplier: 'Supplier',
    customer: 'Customer',
    supplierAndCustomer: 'Supplier + Customer',
    
    // 인보이스 관리
    invoiceManagement: 'Invoice Management',
    invoiceList: 'Invoice List',
    invoiceCreate: 'Invoice Create',
    invoiceApprove: 'Invoice Approve',
    
    // 결제 관리
    paymentManagement: 'Payment Management',
    paymentList: 'Payment List',
    paymentWrite: 'Payment Write',
    paymentApprove: 'Payment Approve',
    
    // 전자 결재
    electronicApproval: 'Electronic Approval',
    
    // 업무 관리
    workManagement: 'Work Management',
    workList: 'Work List',
    workCreate: 'Create Work',
    workEdit: 'Edit Work',
    workDelete: 'Delete Work',
    workTitle: 'Work Title',
    workDescription: 'Work Description',
    workStatus: 'Work Status',
    workPriority: 'Priority',
    workAssignee: 'Assignee',
    workAssigner: 'Assigner',
    workCategory: 'Work Type',
    workDueDate: 'Due Date',
    workStartDate: 'Start Date',
    workCreatedAt: 'Assigned Date',
    workUpdatedAt: 'Updated Date',
    workComments: 'Comments',
    addComment: 'Add Comment',
    noWorks: 'No work items found.',
    workAccept: 'Accept Work',
    workReject: 'Reject Work',
    workAttachments: 'Attachments',
    addAttachment: 'Add Attachment',
    
    // 업무 상태
    workPending: 'Pending Acceptance',
    workAccepted: 'Accepted',
    workInProgress: 'In Progress',
    workCompleted: 'Completed',
    workRejected: 'Rejected',
    
    // 업무 우선순위
    workLow: 'Low',
    workNormal: 'Normal',
    workHigh: 'High', 
    workUrgent: 'Urgent',
    
    // 업무 카테고리
    workGeneral: 'General Work',
    workProject: 'Project',
    workMeeting: 'Meeting',
    workReport: 'Report',
    workPlanning: 'Planning',
    workReview: 'Review',
    electronicApprovalRequest: 'Electronic Approval Request Form',
    electronicApprovalRequestDetails: 'Electronic Approval Request Details',
    requestedApprovals: 'Requested Approvals',
    receivedApprovals: 'Received Approvals',
    myRequestedApprovals: 'My Requested Approvals',
    myReceivedApprovals: 'My Received Approval Requests',
    approvalRequest: 'Approval Request',
    approvalDetails: 'Approval Request Details',
    createApprovalRequest: 'Create Approval Request',
    approvalTitle: 'Title',
    approvalContent: 'Content',
    approvalPriority: 'Priority',
    approvalDueDate: 'Due Date',
    approvalStatus: 'Status',
    approvalRequester: 'Requester',
    approvalApprover: 'Approver',
    approvalRequestNumber: 'Request Number',
    approvalRequestDate: 'Request Date',
    approvalCurrentStatus: 'Current Status',
    approvalPending: 'Pending Approval',
    approvalApproved: 'Approved',
    approvalRejected: 'Rejected',
    approvalHigh: 'High',
    approvalMedium: 'Medium',
    approvalLow: 'Low',
    approvalFiles: 'Attached Files',
    attachedFiles: 'Attached Files',
    fileAttachment: 'File Attachment',
    downloadFile: 'Download File',
    approvalComments: 'Comments',
    commentsAndHistory: '4. Comments And Processing History',
    processingHistory: 'Processing History',
    processingHistoryCount: 'Processing History ({count} Items):',
    attachedFilesCount: 'Attached Files ({count} Items):',
    commentPlaceholder: 'Enter Your Comment (Enter: Submit, Shift+Enter: New Line)',
    registerComment: 'Register',
    approvalCompleted: 'This Is A Completed Approval Request. No More Comments Can Be Added.',
    approvalRejectedComment: 'This Is A Rejected Request. No More Comments Can Be Added.',
    noCommentsYet: 'No Comments Yet.',
    reassignApproval: 'Reassign Approval',
    reassignToOtherApprover: 'Reassign to Another Approver',
    reassignToAnotherApprover: 'You Can Reassign The Approval To Another Approver.',
    newApprover: 'New Approver',
    selectNewApprover: 'Select a new approver...',
    noAvailableApprovers: 'No available approvers',
    reassignReason: 'Reassignment Reason',
    reassignReasonPlaceholder: 'Enter Reassignment Reason (Optional)',
    performReassign: 'Perform Reassignment',
    reassignment: 'Reassignment',
    reassignmentWaiting: 'Awaiting Approval',
    confirmApproval: 'Approve',
    rejectApproval: 'Reject',
    approveRequest: 'Approve',
    rejectRequest: 'Reject',
    requestApproval: 'Request Approval',
    detailedContent: 'Detailed Content',
    requestReason: 'Enter The Reason And Details For The Approval Request',
    titlePlaceholder: 'Enter Request Title',
    selectApprover: 'Select An Approver',
    dueDateHelper: 'If Not Selected, It Will Be Automatically Set To 3 Days Later',
    documentNumber: 'Document Number',
    creationDate: 'Creation Date',
    completionDate: 'Expected Completion Date',
    confirmationSection: 'Confirmation Section',
    categorySection: 'Category',
    fullName: 'Full Name',
    confirmation: 'Confirmation',
    requestConfirm: 'Request',
    approvalWaiting: 'Awaiting Approval',
    approvalInfo: 'Approval Information',
    requestContent: 'Request Content',
    attachments: 'Attachments',
    viewAll: 'View All',
    searchApprovalPlaceholder: 'Search By Title, Requester, Approver...',
    noApprovals: 'No Approval Requests Found.',
    documentInformation: 'Document Information',
    requestedPayments: 'My Requested Payments',
    receivedPaymentRequests: 'My Received Payment Requests',
    completionDueDate: 'Completion Due Date',
    
    // 대시보드 추가 번역
    dashboardTitle: 'Dashboard',
    recentActivity: 'Recent Activity',
    systemPerformance: 'System Performance',
    myRequestedPayments: 'Approvals I Requested',
    myReceivedPaymentRequests: 'Approvals Assigned To Me',
    
    // 문서 정보 관련
    department: 'Department',
    general: 'General',
    
    // 섹션 제목
    requestContentSection: '1. Request Content',
    approvalInfoSection: '2. Approval Information',
    attachmentSection: '2. Attachments',
    confirmationSectionTitle: '3. Confirmation',
    
    // 폼 라벨
    titleLabel: 'Title *',
    detailedContentLabel: 'Detailed Content *',
    approverLabel: 'Approver *',
    priorityLabel: 'Priority',
    dueDateLabel: 'Due Date',
    
    // 테이블 헤더
    categoryHeader: 'Category',
    nameHeader: 'Name',
    dateHeader: 'Date',
    confirmationHeader: 'Confirmation',
    
    // 상태 및 메시지
    approvalWaitingStatus: 'Awaiting Approval',
    requestStatus: 'Request',
    selectApproverPlaceholder: 'Select An Approver',
    approverReassigned: 'Approver Has Been Reassigned.',
    dueDateAutoSet: '* If Not Selected, It Will Be Automatically Set To 3 Days Later',
    
          // 대시보드 인사말 및 상태
      welcomeMessage: 'Hello, {name}!',
      systemStatusNormal: 'Normal',
      allServicesActive: 'All services are operational',
      
      // 공지사항
      notice: 'Notice',
      noticeList: 'Notice List',
      noticeCreate: 'Create Notice',
      noticeEdit: 'Edit Notice',
      noticeDelete: 'Delete Notice',
      noticeTitle: 'Title',
      noticeContent: 'Content',
      noticeAuthor: 'Author',
      noticePriority: 'Priority',
      noticePriorityHigh: 'High',
      noticePriorityMedium: 'Medium',
      noticePriorityLow: 'Low',
      noticePinned: 'Pinned Notice',
      noticeStartDate: 'Start Date',
      noticeEndDate: 'End Date',
      noticeViewCount: 'View Count',
      noticeCreatedAt: 'Created At',
      noticeActions: 'Actions',
      noticeView: 'View',
      noticeEditAction: 'Edit',
      noticeDeleteAction: 'Delete',
      noticeDeleteConfirm: 'Are you sure you want to delete this notice?',
      noticeSearch: 'Search',
      noticeSearchPlaceholder: 'Search by title or content',
      noticeFilterAll: 'All',
      noticeFilterPriority: 'Priority',
      noticeClearSearch: 'Clear',
      noticeTotal: 'Total {count} notices',
    menuPermissions: 'Menu Permissions',
    systemStatusTitle: 'System Status',
    noReceivedRequests: 'No received payment requests',
    
    // 시간 표시
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    dayAgo: 'day ago',
    daysAgo: 'days ago',
    
    // 승인 상태
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    
    // 통계 라벨
    adminCount: 'Admins',
    activeCount: 'Active',
    totalCount: 'Total',
    unit: '',
    unitPeople: '',
    unknown: 'Unknown',
    
    // 전자결재 페이지 추가 번역
    listDescription: 'List',
    receivedApprovalsDescription: 'List of approvals I need to approve',
    statusFilter: 'Status',
    waitingForApproval: 'Waiting',
    currentStatus: 'Current Status',
    rejectedStatus: 'Rejected',
    dueDate: 'Due Date',
    
    // 대시보드 통계
    totalUsers: 'Total Users',
    totalMenus: 'Total Menus',
    registeredCompanies: 'Registered Companies',
    permissionSettings: 'Permission Settings',
    admin: 'Admin',
    regular: 'Regular',
    topLevel: 'Top Level',
    subMenus: 'Sub Menus',
    recentUsers: 'Recent Users',
    systemInfo: 'System Info',
    currentTime: 'Current Time',
    userRole: 'User Role',
    companyId: 'Company ID',
    systemStatus: 'Check system status at a glance',
    searchPlaceholder: 'Search by company name, COI, address, PAN, etc.',
    partnerSearchPlaceholder: 'Search by partner name, COI, address, PAN, product category, etc.',
    roleSearchPlaceholder: 'Search by role name, description, level, company access, etc.',
    noSearchResults: 'No search results found',
    searchResults: 'results',
    notifications: 'Notifications',
    loading: 'Loading menus...',

    // Dashboard replacement card
    approvalOverview: 'Approval Overview',
    toApprove: 'To Approve',
    requested: 'Requested',
    
    // 로그인 페이지
    login: 'Login',
    username: 'Username',
    password: 'Password',
    loginButton: 'Login',
    loginError: 'Login failed.',
    invalidCredentials: 'Invalid username or password.',
    welcomeToManagementSystem: 'Welcome to Management System',
    enterAccountInfo: 'Please enter your account information',
    defaultAccount: 'Default account: root / admin',
    
    // 시스템 초기화
    systemInitialization: 'System Initialization',
    initializeSystem: 'Initialize System',
    systemInitDescription: 'Initialize the system to configure basic settings.',
    initSuccess: 'System initialization completed successfully.',
    initError: 'An error occurred during system initialization.',
    createInitialAdminAccount: 'Create initial administrator account.',
    passwordMismatch: 'Passwords do not match.',
    confirmPassword: 'Confirm Password',
    initialize: 'Initialize',
    companyInfo: 'Company Information',
    adminAccount: 'Administrator Account',
    menuStructure: 'Menu Structure',
    
    // 예시 페이지
    examplePageTitle: 'Example Page',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    dataLoadError: 'Failed to load data.',
    deleteConfirm: 'Are you sure you want to delete?',
    deleteError: 'An error occurred while deleting.',
    saveError: 'An error occurred while saving.',
    id: 'ID',
    name: 'Name',
    description: 'Description',
    actions: 'Actions',
    
    // 사용자 목록 페이지
    userListDescription: 'You can view the list of registered users.',
    noUsers: 'No users registered.',
    userDelete: 'Delete User',
    userDeleteConfirm: 'Delete User Confirmation',
    userDeleteMessage: 'Are you sure you want to delete this user?',
    userDeleteWarning: 'This action cannot be undone.',
    userCreateDate: 'Create Date',
    userUpdateDate: 'Update Date',
    
    // 메뉴 권한 관리
    menuPermissionDescription: 'You can manage user permissions by menu.',
    menuTree: 'Menu Tree',
    menuName: 'Menu Name',
    menuNameEn: 'Menu Name (English)',
    menuUrl: 'Menu URL',
    menuDescription: 'Menu Description',
    menuOrder: 'Menu Order',
    menuIcon: 'Menu Icon',
    menuParent: 'Parent Menu',
    menuChildren: 'Child Menu',
    menuAdd: 'Add Menu',
    menuEdit: 'Edit Menu',
    menuDelete: 'Delete Menu',
    menuMoveUp: 'Move Up',
    menuMoveDown: 'Move Down',
    menuDeleteConfirm: 'Delete Menu Confirmation',
    menuDeleteMessage: 'Are you sure you want to delete this menu?',
    menuDeleteWarning: 'This action cannot be undone.',
    menuAddSuccess: 'Menu added successfully.',
    menuEditSuccess: 'Menu edited successfully.',
    menuDeleteSuccess: 'Menu deleted successfully.',
    menuMoveSuccess: 'Menu order changed successfully.',
    
    // 공통
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    search: 'Search',
    filter: 'Filter',
    refresh: 'Refresh',
    export: 'Export',
    import: 'Import',
    download: 'Download',
    upload: 'Upload',
    view: 'View',
    details: 'Details',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    enabled: 'Enabled',
    disabled: 'Disabled',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    none: 'None',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    required: 'Required',
    optional: 'Optional',
    submit: 'Submit',
    reset: 'Reset',
    clear: 'Clear',
    select: 'Select',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    sort: 'Sort',
    sortAsc: 'Ascending',
    sortDesc: 'Descending',
    page: 'Page',
    of: 'of',
    items: 'items',
    perPage: 'per page',
    showing: 'Showing',
    to: 'to',
    from: 'from',
    total: 'Total',
    empty: 'Empty',
    noData: 'No data available',
    retry: 'Retry',
    reload: 'Reload',
    copy: 'Copy',
    paste: 'Paste',
    cut: 'Cut',
    undo: 'Undo',
    redo: 'Redo',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit Fullscreen',
    preferences: 'Preferences',
    help: 'Help',
    about: 'About',
    contact: 'Contact',
    support: 'Support',
    feedback: 'Feedback',
    report: 'Report',
    analytics: 'Analytics',
    home: 'Home',
    account: 'Account',
    security: 'Security',
    privacy: 'Privacy',
    terms: 'Terms',
    policy: 'Policy',
    copyright: 'Copyright',
    version: 'Version',
    build: 'Build',
    date: 'Date',
    time: 'Time',
    datetime: 'Date & Time',
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ko');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 